# Translation of Odoo Server.
# This file contains the translation of the following modules:
# * login_serial
# 
# Translators:
# Juan José Scarafía <scarafia.juanjose@gmail.com>, 2016
# Nicolas Mac Rouillon <nmr@ingadhoc.com>, 2017
msgid ""
msgstr ""
"Project-Id-Version: Odoo Server 9.0c\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2016-12-28 12:29+0000\n"
"PO-Revision-Date: 2016-12-28 12:29+0000\n"
"Last-Translator: Nicolas Mac Rouillon <nmr@ingadhoc.com>, 2017\n"
"Language-Team: Spanish (https://www.transifex.com/adhoc/teams/46451/es/)\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: \n"
"Language: es\n"
"Plural-Forms: nplurals=2; plural=(n != 1);\n"

#. module: login_serial
#: code:addons/login_serial/res_partner.py:57
#: code:addons/login_serial/res_users.py:29
#, python-format
msgid "Cannot generate Serial Id"
msgstr "No se puede generar el Serial ID"

#. module: login_serial
#: model:ir.ui.view,arch_db:login_serial.view_users_form_login_serial
msgid "Generate new Serial Id"
msgstr "Generar Serial Id"

#. module: login_serial
#: model:ir.ui.view,arch_db:login_serial.login
msgid "Log in"
msgstr "Ingresar"

#. module: login_serial
#: model:ir.ui.view,arch_db:login_serial.login_layout
msgid "Manage Databases"
msgstr "Gestionar Bases de Datos"

#. module: login_serial
#: code:addons/login_serial/res_partner.py:58
#: code:addons/login_serial/res_users.py:30
#, python-format
msgid ""
"Odoo was unable to generate a fresh random Serial Id. It may be that there "
"are a big amount of Serial Id already generated. You can try again."
msgstr ""
"Odoo no pudo generar un ID de serie nuevo. Podría ser debido a que hay una "
"gran cantidad de ID de serie ya generado.  Puedes intentarlo de nuevo."

#. module: login_serial
#: model:ir.model,name:login_serial.model_res_partner
msgid "Partner"
msgstr "Partner"

#. module: login_serial
#: model:ir.ui.view,arch_db:login_serial.login_layout
msgid "Powered by <span>Odoo</span>"
msgstr "Powered by <span>Odoo</span>"

#. module: login_serial
#: model:ir.model.fields,field_description:login_serial.field_res_partner_serial_id
#: model:ir.model.fields,field_description:login_serial.field_res_users_serial_id
#: model:ir.ui.view,arch_db:login_serial.login
#: model:ir.ui.view,arch_db:login_serial.view_users_form_login_serial
msgid "Serial Id"
msgstr "ID serial"

#. module: login_serial
#: code:addons/login_serial/res_partner.py:45
#, python-format
msgid "Serial Id invalid format"
msgstr "Formato Inválido del Id de serie"

#. module: login_serial
#: code:addons/login_serial/res_partner.py:46
#, python-format
msgid "The Serial Id field has not the EAN-13 format standard."
msgstr "El Id de Serie no posee el formato estándar de EAN-13"

#. module: login_serial
#: code:addons/login_serial/res_partner.py:28 sql_constraint:res.partner:0
#, python-format
msgid "There is another user with this Serial Id."
msgstr "Hay otro usuario con este mismo ID serial"

#. module: login_serial
#: model:ir.model,name:login_serial.model_res_users
msgid "Users"
msgstr "Usuarios"

#. module: login_serial
#: code:addons/login_serial/controllers/main.py:91
#, python-format
msgid "Wrong Serial Id"
msgstr "Id de serie erróneo"

#. module: login_serial
#: model:ir.ui.view,arch_db:login_serial.view_partner_form
msgid "⇒ Generate new Serial Id"
msgstr "⇒ Generar nuevo ID de serie"
